# Generated by Django 6.0.6 on 2026-07-03 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membres",
                    models.ManyToManyField(
                        related_name="projets_rejoints", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("todo", "À faire"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("moyenne", "Moyenne"),
                            ("haute", "Haute"),
                        ],
                        default="moyenne",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taches_assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="projects.projet",
                    ),
                ),
            ],
        ),
    ]
